application: gamenightvote
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /votenight.*
  script: votenight.application
- url: /.*
  script: votenight.application
- url: /tasks/tally
  script: votenight.application
  # login: admin
- url: /tasks/initdb
  script: votenight.application
  # login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest