application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /table_test.*
  script: table_test.application
- url: /.*
  script: table_test.application
- url: /tasks/tally
  script: tally.application
  # login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest